name: Release & Publish to pub.dev

on:
  push:
    tags:
      - 'v*'  # Tag pattern on pub.dev: 'v{{version}}'

jobs:
  release:
    permissions:
      id-token: write  # Required for OpenID Connect
      contents: write   # Required for creating releases
    runs-on: ubuntu-latest

    steps:
      - name: Validate branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Error: This workflow can only be run on the main branch."
            exit 1
          fi

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install Node.js dependencies
        run: npm ci

      - name: Publish package
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}  # Assuming you store your token here
        run: |
          dart pub get
          echo "Publishing package..."
          dart pub publish -f

      - name: Print success message
        if: success()
        run: echo "Release and publishing completed successfully!"

      - name: Handle failure
        if: failure()
        run: echo "Release process failed."
