name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Specify release type: regular, alpha, beta, or rc'
        required: true
        default: 'regular'
        type: choice
        options:
          - regular
          - alpha
          - beta
          - rc

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      actions: write

    env:
      RELEASE_TYPE: ${{ github.event.inputs.release-type }}
      GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB }}

      - run: npm ci

      - name: Set Git user
        run: |
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

      - name: Run release-it
        run: |
          if [ "$RELEASE_TYPE" == "regular" ]; then
            npx release-it --ci
          else
            npx release-it --ci --preRelease="$RELEASE_TYPE"
          fi
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}